# ----------- CONFIGURABLE START -----------
title:            "Catsay's blog"
description:      "独立开发者|欢迎来到 Catsay「角落」侃侃理想、谈谈人生、敲敲代码。"
url:              http://www.fuckhnsfjy.com/ # 域名
signoff:          "Catsay" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         安全
    url:          /book
    external:     false
  - name:         生活
    url:          /road
    external:     false
  - name:         归档
    url:          /archives
    external:     false
  - name:         标签
    url:          /tags
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
